before_script:
    - composer self-update
    - composer install
language: php
services: redis-server
branches:
  only:
  - master
php:
    - 7.1
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
